[project]
name = "hello-world-api"
version = "0.1.0"
description = "A basic Flask API call to display Hello world"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.5",
]
